# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-07 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysale', '0002_auto_20180307_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='owner_email',
            new_name='newsletter_email',
        ),
    ]
