# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-08 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysale', '0003_auto_20180307_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=80)),
                ('contact_mobile', models.CharField(max_length=10)),
                ('contact_message', models.CharField(max_length=200)),
            ],
        ),
    ]
