# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysale', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_message',
            field=models.TextField(max_length=200),
        ),
    ]
